export const imagesH = [
  "/hCarousel/hor1.jpg",
  "/hCarousel/hor3.jpg",
  "/hCarousel/hor4.jpeg",
  "/hCarousel/hor5.jpg",
  "/hCarousel/hor6.jpeg",
  "/hCarousel/hor7.jpg",
  "/hCarousel/hor8.jpeg",
  "/hCarousel/hor9.jpg",
  "/hCarousel/hor10.jpg",
  "/hCarousel/hor11.jpg",
  "/hCarousel/hor12.jpg",
  "/hCarousel/hor13.jpg",
  "/hCarousel/hor14.jpg",
  "/hCarousel/hor15.jpg",
  "/hCarousel/hor16.jpg",
  "/hCarousel/hor17.jpg",
  "/hCarousel/hor18.jpg",
  "/hCarousel/hor19.jpg",
  "/hCarousel/hor20.jpg",
  "/hCarousel/hor21.jpg",
  "/hCarousel/hor22.jpg",
  "/hCarousel/hor23.jpg",
  "/hCarousel/hor24.jpg",
  "/hCarousel/hor25.jpg",
  "/hCarousel/hor26.jpg",
  "/hCarousel/hor27.jpg",
  "/hCarousel/hor28.jpg",
  "/hCarousel/hor29.jpg",
  "/hCarousel/hor30.jpg",
  "/hCarousel/hor31.jpg",
  "/hCarousel/hor32.jpg",
  "/hCarousel/hor33.jpg",
  "/hCarousel/hor34.jpg",
  "/hCarousel/hor35.jpg",
  "/hCarousel/hor36.jpg",
  "/hCarousel/hor37.jpg",
  "/hCarousel/hor38.jpg",
  "/hCarousel/hor39.jpg",
  "/hCarousel/hor40.jpg",
  "/hCarousel/hor41.jpg",
];
export const altTextsH = [
  "Men's team photo",
  "Men's team game pep talk",
  "Under 14s team photo",
  "Team members hugging one another",
  "Under 18s team photo",
  "Men's team photo",
  "men's team photo",
  "A founder high fiving the team",
  "Group chanting before a game",
  "Team photo",
  "Team photo celebrating",
  "A player about to pass the ball",
  "Player shooting a basketball",
  "Referee managing the game",
  "Player dribbling the ball",
  "Players during a game",
  "Players during a game",
  "A player talking to the referee",
  "Oppiste team in possession of the ball",
  "Youth team in training session",
  "Youth team in friendly game",
  "Player ready to shoot the ball",
  "Player passing the ball",
  "Players during a game",
  "Player ready to shoot the ball",
  "Team photo celebrating a win",
  "Team photo during a social engagement",
  "A player in action",
  "A player ready to shoot the ball",
  "Team motivational chant",
  "Players viewing the game from the side line",
  "Player shooting the ball",
  "Players watching from the side line",
  "A player navigating defenders during a game",
  "Kings Heath Clangers players defending during a game",
  "Adult team playing a game",
  "Team strategy talk",
  "Team during play",
  "Team photo",
  "Team and public supporting the team from the side lines",
  "Team photo",
];
