const imagesV = [
'public/vCarousel/Vert (1).jpg',
'public/vCarousel/Vert (2).jpg',    
'public/vCarousel/Vert (3).jpg',
'public/vCarousel/Vert (4).jpg',
'public/vCarousel/Vert (5).jpg',
'public/vCarousel/Vert (6).jpg',
'public/vCarousel/Vert (7).jpg',
'public/vCarousel/Vert (8).jpg',
'public/vCarousel/Vert (9).jpg',
'public/vCarousel/Vert (10).jpg',
'public/vCarousel/Vert (11).jpg',
'public/vCarousel/Vert (12).jpg',  
'public/vCarousel/Vert (13).jpg',
'public/vCarousel/Vert (14).jpg',
'public/vCarousel/Vert (15).jpg',
'public/vCarousel/Vert (16).jpg',
'public/vCarousel/Vert (17).jpg',
'public/vCarousel/Vert (18).jpg',
'public/vCarousel/Vert (19).jpg',
'public/vCarousel/Vert (20).jpg',
'public/vCarousel/Vert (21).jpg',
'public/vCarousel/Vert (22).jpg',
'public/vCarousel/Vert (23).jpg',
'public/vCarousel/Vert (24).jpg',
'public/vCarousel/Vert (25).jpg',
'public/vCarousel/Vert (26).jpg',
'public/vCarousel/Vert (27).jpg',
'public/vCarousel/Vert (28).jpg',
'public/vCarousel/Vert (29).jpg',
'public/vCarousel/Vert (30).jpg',
'public/vCarousel/Vert (31).jpg',
'public/vCarousel/Vert (32).jpg',
'public/vCarousel/Vert (33).jpg',
'public/vCarousel/Vert (34).jpg',
'public/vCarousel/Vert (35).jpg',
'public/vCarousel/Vert (36).jpg',
'public/vCarousel/Vert (37).jpg',
'public/vCarousel/Vert (38).jpg',
'public/vCarousel/Vert (39).jpg',
'public/vCarousel/Vert (40).jpg',
'public/vCarousel/Vert (41).jpg'
];

export default imagesV;
