const imagesH = [
    '../../public/hCarousel/Hor1.jpeg',
    '../public/hCarousel/Hor (1).jpg',
    'public/hCarousel/Hor (2).jpeg',
    'public/hCarousel/Hor (2).jpg',
    'public/hCarousel/Hor (3).jpeg',
    'public/hCarousel/Hor (3).jpg',
    'public/hCarousel/Hor (4).jpeg',
    'public/hCarousel/Hor (4).jpg',
    'public/hCarousel/Hor (5).jpeg',
    'public/hCarousel/Hor (5).jpg',
    'public/hCarousel/Hor (6).jpg',
    'public/hCarousel/Hor (7).jpg',
    'public/hCarousel/Hor (8).jpg',
    'public/hCarousel/Hor (9).jpg',
    'public/hCarousel/Hor (10).jpg',
    'public/hCarousel/Hor (11).jpg',
    'public/hCarousel/Hor (12).jpg',
    'public/hCarousel/Hor (13).jpg',
    'public/hCarousel/Hor (14).jpg',
    'public/hCarousel/Hor (15).jpg',
    'public/hCarousel/Hor (16).jpg',
    'public/hCarousel/Hor (17).jpg',
    'public/hCarousel/Hor (18).jpg',
    'public/hCarousel/Hor (19).jpg',
    'public/hCarousel/Hor (20).jpg',
    'public/hCarousel/Hor (21).jpg',
    'public/hCarousel/Hor (22).jpg',
    'public/hCarousel/Hor (23).jpg',
    'public/hCarousel/Hor (24).jpg',
    'public/hCarousel/Hor (25).jpg',
    'public/hCarousel/Hor (26).jpg',
    'public/hCarousel/Hor (27).jpg',
    'public/hCarousel/Hor (28).jpg',
    'public/hCarousel/Hor (29).jpg',
    'public/hCarousel/Hor (30).jpg',
    'public/hCarousel/Hor (31).jpg',
    'public/hCarousel/Hor (32).jpg',
    'public/hCarousel/Hor (33).jpg',
    'public/hCarousel/Hor (34).jpg',
    'public/hCarousel/Hor (35).jpg',
    'public/hCarousel/Hor (36).jpg',
    'public/hCarousel/Hor (37).jpg',
    'public/hCarousel/Hor (38).jpg',
    'public/hCarousel/Hor (39).jpg',
    'public/hCarousel/Hor (40).jpg',
    'public/hCarousel/Hor (41).jpg',
  ];
  
  export default imagesH;