export const imagesV = [
  "/vCarousel/ver1.jpg",
  "/vCarousel/ver2.jpg",
  "/vCarousel/ver3.jpg",
  "/vCarousel/ver4.jpg",
  "/vCarousel/ver5.jpg",
  "/vCarousel/ver6.jpg",
  "/vCarousel/ver7.jpg",
  "/vCarousel/ver8.jpg",
  "/vCarousel/ver9.jpg",
  "/vCarousel/ver10.jpg",
  "/vCarousel/ver11.jpg",
  "/vCarousel/ver12.jpg",
  "/vCarousel/ver13.jpg",
  "/vCarousel/ver14.jpg",
  "/vCarousel/ver15.jpg",
  "/vCarousel/ver16.jpg",
  "/vCarousel/ver17.jpg",
  "/vCarousel/ver18.jpg",
  "/vCarousel/ver19.jpg",
  "/vCarousel/ver20.jpg",
  "/vCarousel/ver21.jpg",
  "/vCarousel/ver22.jpg",
  "/vCarousel/ver23.jpg",
  "/vCarousel/ver24.jpg",
  "/vCarousel/ver25.jpg",
  "/vCarousel/ver26.jpg",
  "/vCarousel/ver27.jpg",
  "/vCarousel/ver28.jpg",
  "/vCarousel/ver29.jpg",
  "/vCarousel/ver30.jpg",
  "/vCarousel/ver31.jpg",
  "/vCarousel/ver32.jpg",
  "/vCarousel/ver33.jpg",
  "/vCarousel/ver34.jpg",
  "/vCarousel/ver35.jpg",
  "/vCarousel/ver36.jpg",
  "/vCarousel/ver37.jpg",
  "/vCarousel/ver38.jpg",
  "/vCarousel/ver39.jpg",
  "/vCarousel/ver40.jpg",
  "/vCarousel/ver41.jpg",
];

export const altTextsV = [
  "Image of men's basketball game",
  "Image of adult male player in action",
  "Image of adult male player shooting a basketball",
  "Image of adult male player shooting a basketball",
  "Image of adult male player moving around a defensive player",
  "Image of adult male player shooting a basketball into the hoop",
  "Image of adult male player shooting a basketball into the hoop",
  "Image of adult male player moving around a defensive player",
  "Image of adult male player moving around a defensive player",
  "Image of adult male player shooting a basketball",
  "A founder of Kings Heath Clangers Basketball Club",
  "Image of adult male player in action",
  "Image of adult male player celebrating a win",
  "Image of adult male player in action",
  "Image of adult male player shooting a basketball",
  "Image of adult male player shooting a basketball",
  "Image of adult male player shooting a basketball",
  "Image of adult male player shooting a basketball",
  "Image of adult male player dribbling a basketball",
  "Image of adult male player shooting a basketball",
  "Image of opposing team defending against a player",
  "Image of opposing team defending the basket",
  "Image of adult male player passing a basketball",
  "Image of players discussing their game",
  "Image of a team talk during a game",
  "Image of a founder of Kings Heath Clangers Basketball Club supporting a game",
  "Image of players holding a trophy",
  "Image of a founder talking to the referee",
  "Image of adult male player shooting a basketball",
  "Image of a founder watching a game",
  "Image of adult male player shooting a basketball",
  "Image of the team watching from the side lines",
  "Image of player running with the ball",
  "Image of player moving around a defensive player",
  "Image of a player and coach watching from the side line",
  "Image of a player getting ready to play",
  "Image of adult male player shooting a basketball",
  "Image of both teams competing for the ball",
  "Image of player running with the ball",
  "Image of players high-fiving after a win",
  "Image of adult male player shooting a basketball",
];
