import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Header from "../../components/header/header.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${styles.container} ${inter.className}`}>
        {children}
        <Header />
      </body>
    </html>
  );
}
