import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page.js";
import AddGame from "./addGame.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Home />
        <AddGame />
      </body>
    </html>
  );
}
